language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

script:
- sbt ++$TRAVIS_SCALA_VERSION mdocValidate
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- sbt ++$TRAVIS_SCALA_VERSION mdocPublishDeb
deploy:
  provider: bintray
  file: deploy.json
  user:
    secure: ASkNwvxeXEphxt65hh5wToMegKB2vs6Cje8PNejP19XMcoFaomZyE5JP/VXHM8DbDAwy8z/mmt/sBU/sOfrBjOtXUBcxQYSt6SQifnWmivIgKKtBVA5SNfGohuFBzp3rvQBoVbeM0pkGK16QMiwiDHl9HbDZRZ8txxGeIxl4HjrIuABJrY9ojgARzPXJ4xemPZPg3U+/fPKxd1ixWFW1/rfOQoHothWeocIUVMrarlxlWq679nQ61M9V9GL2chVa/hTe5iDl9ccQZocdcQRptF/5cHHolUCZ9LCgM/xPMk82dtaChEj6BrKuYXGO6yv/Hf0SDVhfjG+IBMK3W0nJcdb4HXgRtk/zcbP4r9/z2Ggl5QnKIRGdd8MpSgASc9Li/sAKzB1dfP7OtYvL199cG9fD7STxlL8/3oli0eqtQt4wi0d+3Sd3c2YcfwmwTjHoTeHHJjOfTg0G1Z96wYCggEsxxwtOQIjE/wZ1Qoojv2jUYtgCefrVhM7KoL+T4gjXMl6xExI8FN3yV/yn1f+kPkpDoRjpu/nxKd4px3DBxBxD91PF11ZRTbrq686Xy1mxd8p05b5ypSbRcWbUXhKeeFwJZ+LprTvR6T9VlksoX6cx8IUCwnwBtbTFk3sTqSWzQQegjk4I6fUTuFGABtYq/Xrr4snzXt/tZn1ulq8vo6Y=
  key:
    secure: QWyrfPqX1GkAY2q+PRpg+Ryo/XngE40UqAqyOtSvr9Plc71Mr5GvZoTR2qOl8Z49v4dCn/bxFAqIv60mBSyAS9YCdps+Z0d50k9t4ndRirajtVxROtjrBsODoT1zugllxLXnlWPbtsqzE8uceVa409Tb7EyBhIe3+FR1JNfu4dHpVk4jJUptrCdZ9Y3c9Y4wKmdukxoAbhua50T4F3tYFpOGjtWvX7+kbmo+fbTiYJc9L8sXwc/zGEdWF+qcLuZ4qs1n6yRxzipAjYhguYbirYcbaED/nTfw/nspT8vnB8IqdU7xAy681bWkPfbecxtFaO+xeLhHfhcWWOyi7whXBBCn+7DZ3yvc44nl0hD/lLYrmDbHsqulenXwVvTIjr+TOWxYEDlOCyYIM0jBjhXI+g3xG8W+j8zeLqstgHv48dj46R17krlYUqK/30321phhGPw0XvC90yjVgKqLh4QsCN3h3nNMLap1pp3QP0V2+1xWLzH0fbMYEVKHVQ9EKaxZn30kT3fesnh3owRX72gcKGBAyfEM2w/DCBoFJZP6Y06AFTfaj4kMtuFbnv+ibZw57zQAqm0//2nwYOS2DoBazAHpLlQTM+DIEjtkFCbC2ZRM/hHuof/vt8Gy8loC7K90WiyFcfwcVO7OwcdL/eKohykvxkzAEfSb9H9blkHo+n0=
after_deploy:
- cd scripts && sh cloud-install.sh

before_install:
- openssl aes-256-cbc -K $encrypted_47b971784cbb_key -iv $encrypted_47b971784cbb_iv
  -in scripts/cloud-identity.enc -out scripts/cloud-identity -d

env:
  global:
    secure: GKpcwjgPnzyZnTvPZR2uAn1pUecMBdEUjeScIJMYlT6jkin625JDwY8BHN12ONaHVj2/cBQguKZwlpOX5qr/d8K/9I4vqqQpZIUgUf1C87xOnFNNHSV36UCpK5TvmFMKZefnFhVG2roWxz0l+e/8XJcnvRz88LLcJEC04ga4r89eH13EXJopSVSD3Q+QEAOUaZJE6DXy3KbmPtSGWy8zo8efY/+ctihU0IizVPWgtcPbvS6ECf4eWaSWnQ5urUOTblTkkh5TiX8c0ngTTIHclJoR/+Ejg/sgbKISA2ruRcAEExO2wYysrRNjrUQYo6xEUTbBE5HDGg5nmWFP2NQuR34EaeXsB/QntmH9RBApGCKlZN33M40+abyx6hizgHfkteLC0P3cOXyIg9N1rFUiWldSUAGE75YYPGTLl1qeCQ6hF1z3gsPEraUlwH4srrpebD6LQxoWvczDxaJEmUJZnLoVAlHnvxAeUsCcdi/aW5RxeSgu46SRk/zzNHDS1FJZq1UE9cIneHqWDDxwYeYN1nyXInvgL7e0m/k5mPEcTmzCiSXx2mb6pzOysaznStY24sMTNMkppIztD5jW4luQVh0sEDCXD2lmReaTyqNfEyHqyWt4EFzTw9IdXfPaVUlsWlQhQqVvbws496lOnMkqPX/p5EljpkL4UsuEuOwMDqM=

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
