language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8

sudo: false
addons:
  apt:
    packages:
    - graphviz

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

script:
- sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- sbt ++$TRAVIS_SCALA_VERSION mdocPublishDeb
deploy:
  provider: bintray
  file: deploy.json
  user:
    secure: ASkNwvxeXEphxt65hh5wToMegKB2vs6Cje8PNejP19XMcoFaomZyE5JP/VXHM8DbDAwy8z/mmt/sBU/sOfrBjOtXUBcxQYSt6SQifnWmivIgKKtBVA5SNfGohuFBzp3rvQBoVbeM0pkGK16QMiwiDHl9HbDZRZ8txxGeIxl4HjrIuABJrY9ojgARzPXJ4xemPZPg3U+/fPKxd1ixWFW1/rfOQoHothWeocIUVMrarlxlWq679nQ61M9V9GL2chVa/hTe5iDl9ccQZocdcQRptF/5cHHolUCZ9LCgM/xPMk82dtaChEj6BrKuYXGO6yv/Hf0SDVhfjG+IBMK3W0nJcdb4HXgRtk/zcbP4r9/z2Ggl5QnKIRGdd8MpSgASc9Li/sAKzB1dfP7OtYvL199cG9fD7STxlL8/3oli0eqtQt4wi0d+3Sd3c2YcfwmwTjHoTeHHJjOfTg0G1Z96wYCggEsxxwtOQIjE/wZ1Qoojv2jUYtgCefrVhM7KoL+T4gjXMl6xExI8FN3yV/yn1f+kPkpDoRjpu/nxKd4px3DBxBxD91PF11ZRTbrq686Xy1mxd8p05b5ypSbRcWbUXhKeeFwJZ+LprTvR6T9VlksoX6cx8IUCwnwBtbTFk3sTqSWzQQegjk4I6fUTuFGABtYq/Xrr4snzXt/tZn1ulq8vo6Y=
  key:
    secure: QWyrfPqX1GkAY2q+PRpg+Ryo/XngE40UqAqyOtSvr9Plc71Mr5GvZoTR2qOl8Z49v4dCn/bxFAqIv60mBSyAS9YCdps+Z0d50k9t4ndRirajtVxROtjrBsODoT1zugllxLXnlWPbtsqzE8uceVa409Tb7EyBhIe3+FR1JNfu4dHpVk4jJUptrCdZ9Y3c9Y4wKmdukxoAbhua50T4F3tYFpOGjtWvX7+kbmo+fbTiYJc9L8sXwc/zGEdWF+qcLuZ4qs1n6yRxzipAjYhguYbirYcbaED/nTfw/nspT8vnB8IqdU7xAy681bWkPfbecxtFaO+xeLhHfhcWWOyi7whXBBCn+7DZ3yvc44nl0hD/lLYrmDbHsqulenXwVvTIjr+TOWxYEDlOCyYIM0jBjhXI+g3xG8W+j8zeLqstgHv48dj46R17krlYUqK/30321phhGPw0XvC90yjVgKqLh4QsCN3h3nNMLap1pp3QP0V2+1xWLzH0fbMYEVKHVQ9EKaxZn30kT3fesnh3owRX72gcKGBAyfEM2w/DCBoFJZP6Y06AFTfaj4kMtuFbnv+ibZw57zQAqm0//2nwYOS2DoBazAHpLlQTM+DIEjtkFCbC2ZRM/hHuof/vt8Gy8loC7K90WiyFcfwcVO7OwcdL/eKohykvxkzAEfSb9H9blkHo+n0=
after_deploy:
- cd scripts && sh cloud-install.sh

before_install:
- openssl aes-256-cbc -K $encrypted_47b971784cbb_key -iv $encrypted_47b971784cbb_iv
  -in scripts/cloud-identity.enc -out scripts/cloud-identity -d

env:
  global:
    secure: 3JU/XvDpXOzTnfGEIi7a3n9bmGufgysyxMOeYmTOP3r67kDx4R64PhKHs5pnQ51FegOh5ExEwkW+EeWf95pDQXx2fjU+8gARskeJivIdHhCP4UImJFzm3/8XG6B0rtf2q1jmgwYCSqm8jwPs69gHPS2ybp8ZoQQYKiawN/H2qp6SFU5HMCnwSbH8fv2tsh8KTwVtFFyD36G/toOjRm4pPsyep+v3F7gtnEMxi7okmZ4DM061FHj+/rvC7XhPvY6SxOexW/nfg2oFbhOtzfQgmRDHtWAY9SGMKx5eFnE4AZR+hkFDQAAdL1ybrY+plurx8aUDHllWyLHpJeSdi71RTJDLyRvL2Bz2AwG0AFdbOZhZJpJ3yMeqtz6TKMC4OyikrnUy336kLJApghWAC7y7gldRNY4UrrlMsIxN9ngcdtOa8JC8ZIiq7b43cCBlqyngD+aInoaKyyRHpeZTa2qGD6oV/nyNYjSYzn/TGuEjfkGgItDCxt4mlYuka3gcEuJvzUtS8IBm2JEV5Mj2ZSnHodaA/zWAKOYFmLUrqfwaV3x4KNvHBoENCwxIEcwLYxuU2eLFVxpHAggqfNaXkPSp7iJiVnjyq0x2gIKx9U9aMM+yDbdB24kgewqU/ZIHrJCzH5mFGL0RKU9PL87qVOvxtKvbfi7bwzcVSwNk+enj0Cw=

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
